### PR TITLE
Use Pytest For Testing

### PR DESCRIPTION
**Pull request by davesims**
### Use Pytest

Following https://github.com/kubostech/kubos-cli/issues/4, I think I like [pytest](http://docs.pytest.org/en/latest/contents.html) pretty good, other than the fact that it only does a shallow path load, requiring some awkward workaround-fu. But the test syntax is really simple, as is the test runner.

/cc @kyleparrott @plauche for thoughts.

### CODE REVIEW

**Comment by kyleparrott** [comment]
With the "pathing" issues figured out, it seems like you're on the right track now.

**Comment by kyleparrott** [comment]
@davesims was this a WIP PR or is this ready to look at for merging?

**Comment by kyleparrott** [comment]
@davesims @plauche: I have added a couple of minor things to this PR (mocking up default arguments that yotta passes in from actual cli usage) to get the update test passing.

What would you think of merging in this PR as an example of how we want our future kubos-cli unit tests follow in structure. Then later, in the interest of keeping PR's as small as possible, backfill our existing functionality with future unit test PR's?

**Comment by plauche** [comment]
Does this actually test & verify any real functionality? I'd be ok with just closing this PR and opening a new one with real tests.

**Comment by kyleparrott** [comment]
Making a new PR sounds good to me. This test is trivial at the moment and is not a big deal to abandon. I'm closing this PR and will submit a new one once more test(s) have been completed.

**Pull request closed without merging**
