### PR TITLE
Added unit test for link command

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Added tests for the link command

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
It seems the that CircleCI test that is failing is the integration tests. Do you think that my test has caused the issue?

**Comment by kyleparrott** [comment]
There was a bug that was merged in as part of #21 that was causing some tests to fail 😞 . The fix for that bug was merged just a minute ago and the repo's now green again. 

I would pull the new changes from master and re-verify your tests to make sure that old bug isn't causing your new test to fail still.

**Comment by TheHollidayInn** [comment]
Sounds good! I'll rebase and push

**Comment by kyleparrott** [comment]
There's a little issue with our CD script at the moment (being fixed in #36) once thats merged sometime today, I will merge in this PR.

**Pull request merged**
